### ISSUE TITLE
Dell D3100 Dock, HDMI not working

### ISSUE THREAD

**Issue by andrewwiik** [syscl/XPS9350-macOS#164]
I have tried several different SMBIOS Configurations but I can't seem to get my XPS 9350 to see the monitor connected to my docking station, it sees all the usb devices attached to the docking station however.

**Comment by kdb424** [comment]
Running a vanilla install with only these patches applied (1080p 9350) type C hotplug does not work. Try booting with the dock attached. The dock that I use the display works fine including hotplugging the display (WD15 dock I believe)

**Comment by andrewwiik** [comment]
It isn't a type C connector, it's regular old USB 3.0

**Comment by kdb424** [comment]
https://apple.stackexchange.com/questions/239212/dell-docking-station-d3100-with-macbook-pro
I'm assuming that you already installed the drivers? USB doesn't seem to be an issue on this system, so that comes down to the dock, and not really an issue with dis deploy script. IE, this is probably not the best place for support on non related items.

**Comment by andrewwiik** [comment]
@kdb424 First, THANK YOU SO MUCH, I had looked for days on this and i had never seen that post, it works just fine now, also do you have a paypal I can throw a few bucks to for the help? Thanks again

**Comment by PavelKatunin** [comment]
My MacBook Pro (15-inch, 2017) doesn't see the hub at all.
Sierra 10.12.6

It doesn't appear in About this mac -> System report.

I've installed the newest version of the driver.

It didn't help.
