### ISSUE TITLE
Kernel panic after Security Update 2018-001 10.12.6

### ISSUE THREAD

**Issue by vaites** [syscl/XPS9350-macOS#174]
I installed yesterday the Spectre/Meltdown patch for macOS Sierra and after reboot a kernel panic appears and the laptop reboots. I didn't apply Deploy.sh after update and I recovered the system using my Time Machine...

Someone tried to install the update and had success aplying Deploy.sh?

**Comment by flipphos** [comment]
I had the same problem, which was caused by the lower version of Lilu.
You can upgrade Lilu and its plugins before the Macos upgrade.
Or in case you are experiencing the endless reboot, you can use - liluoff to diable Lilu during in Clover and upgrade Lilu right after the successful boot.
For me, I used the latter method as I already had done the Macos upgrade.

**Comment by vaites** [comment]
Thanks @flipphos, will try updating Lilu as you say.
