### ISSUE TITLE
Freeze on Charging Change - High Sierra

### ISSUE THREAD

**Issue by andrewwiik** [syscl/XPS9350-macOS#199]
Whenever I plug in or unplug my xps macOS freezes up and I have to reboot. 10.13.3

**Comment by bbZCat** [comment]
I have this issue too, but it also happened under win env so i guess it is a hardware bug.

**Comment by andrewwiik** [comment]
My issue only happens on the macOS Env

**Comment by berchca** [comment]
I've been having this problem myself for months now, since I first Hackintoshed my XPS 9350 (regular Sierra). I haven't had any time to work on it, but I suspect it's an ACPI error. If I have my console open and the search string set to 'ACPI' when I unplug my XPS, I get a string of errors, repeated I think four times. The errors appear instantly, and from that moment on, it's only a matter of time before my machine crashes, even if I immediately plug it back in.

 They seem to be related to the following ACPIs (I think these are all ACPIs):
EV9
SMIE
NEVT
_SB_.PCI0.LPCB.ECDV._Q66
PDC0
\PNOT
\_SB_.ADP1._PSR
\_PR_.PPCE

A full error looks like this:
default	07:02:18.863049 -0400	kernel	ACPI Error:
default	07:02:18.863065 -0400	kernel	ACPI Error:
default	07:02:18.863069 -0400	kernel	[CPPC]
default	07:02:18.863071 -0400	kernel	[CPPC]
default	07:02:18.863075 -0400	kernel	 Namespace lookup failure, AE_NOT_FOUND
default	07:02:18.863093 -0400	kernel	 (20140828/psargs-1d1)
default	07:02:18.863176 -0400	kernel	[\EV9_] (Node ffffff8048023290)
default	07:02:18.863179 -0400	kernel	, AE_NOT_FOUND
default	07:02:18.863181 -0400	kernel	, AE_NOT_FOUND
default	07:02:18.863185 -0400	kernel	 (20140828/psparse-270)
default	07:02:18.863187 -0400	kernel	 (20140828/psparse-270)

But editing the list down:
Namespace lookup failure, AE_NOT_FOUND
kernel	 (20140828/psargs-1d1)
kernel	[\EV9_] (Node ffffff8048023290)
kernel	 (20140828/psparse-270)

kernel	Method parse/execution failed
kernel	[\SMIE] (Node ffffff804801f450)
kernel	, AE_NOT_FOUND
kernel	 (20140828/psparse-270)

kernel	Method parse/execution failed
kernel	[\NEVT] (Node ffffff804801fc90)
kernel	, AE_NOT_FOUND
kernel	 (20140828/psparse-270)

kernel	Method parse/execution failed
kernel	[\_SB_.PCI0.LPCB.ECDV._Q66] (Node ffffff804801ef10)
kernel	, AE_NOT_FOUND
kernel	 (20140828/psparse-270)

kernel	[PDC0]
kernel	 Namespace lookup failure, AE_NOT_FOUND
kernel	 (20140828/psargs-1d1)

kernel	Method parse/execution failed
kernel	[\PNOT] (Node ffffff804800be50)
kernel	, AE_NOT_FOUND
kernel	 (20140828/psparse-270)

kernel	Method parse/execution failed
kernel	[\_SB_.ADP1._PSR] (Node ffffff804801fe50)
kernel	, AE_NOT_FOUND
kernel	 (20140828/psparse-270)
kernel	ACPIBatteryManager: ACPIACAdapter: ACPI method _PSR failed

kernel	Method parse/execution failed
kernel	[\_PR_.PPCE] (Node ffffff804801bdd0)
kernel	, AE_NOT_FOUND
kernel	 (20140828/psparse-270)

**Comment by ggctseng** [comment]
I don't know if there has been a solution found for this, but I have the same issue (Random freezes, and freezes with power supply plug/unplug).  Seems to have started when I upgraded bios to 1.7.0.

**Comment by berchca** [comment]
I have not upgraded myself, but I'm curious if you're seeing the same ACPI errors in the console when you unplug? I've done a little debugging, checking the obvious stuff, but of course syscl didn't miss any of those tricks. Hoping to dig a little deeper over the weekend. Unfortunately, I have to figure out what's already been done before I can hope to figure out what hasn't. 

What I know: 
Same error if I don't load any of the SSDTs, as well as the batterymanager kext. 
_STA is set for non-removable battery (which is good).

I'll post anything else I discover.

**Comment by andrewwiik** [comment]
Any update on this?

**Comment by andrewwiik** [comment]
I think we need to change XOSI to WIndows 7 in wherever that matters as i read that somewhere, I just don't know how to do it

**Comment by andrewwiik** [comment]
Actually I got it, create a folder ACPI->patched in your clover install and ad the attached asml file go the patched folder. also go into your config.plist and enable the OSI to -> XOSI patch and it won't freeze on charger plug anymore :) (extract the .aml from the zip of course first)
[SSDT-XOSI.aml.zip](https://github.com/syscl/XPS9350-macOS/files/2337749/SSDT-XOSI.aml.zip)

**Comment by syscl** [comment]
@andrewwiik Thank you so much! Would you mind providing a pull request so that I can merge your improvement?

Thank you in advance,
syscl
