### ISSUE TITLE
Trackpad System Preferance Pane blank

### ISSUE THREAD

**Issue by bdurrow** [syscl/XPS9350-macOS#23]
The trackpad system preference pane is blank.  Additionally the trackpad is very hard to use.  I have read in this guide (https://www.tonymacx86.com/threads/guide-dell-xps-13-9350-macos-10-12-1.204730/) that he found the VoodooPS2Controller (https://github.com/RehabMan/OS-X-Voodoo-PS2-Controller) provides better usability than ApplePS2SmartTouchPad even if it only supports a limited set of gestures.  Have you considered using it instead or as a non-default option? Would you accept a PR that implemented it as an alternative to ApplePS2SmartTouchPad?  If so how would you most like to detect the user's preference for the PS2 driver?  Command line argument? Environment Variable? Presence in kext repo? Node in config.xml?

**Comment by syscl** [comment]
I know both latest AppleSmartTouchPad and VoodooPS2 have fixed the user preference(all credit goes to usr-sse2, a well known hackintosher). 

I've considered implemented VoodooPS2 for this project already, but VoodooPS2 will never possible be implemented in any of my project for the following reason:
- Random lose response during use(do not know why) but obvious RehabMan never plan to fix this issue(he though he has fixed this issue already)
- I asked RehabMan is it possible to implement 3 pinch/tap such that I can remap this to lookup function as a real MacBook, but he told me very concisely - no
- It's weird to customize your gesture through SysPref as VoodooPS2, I know if users can custom their gestures through SysPref, my life will be much easier, but I just want the experience on my project to be consistent and prevent some potential bugs. 
- The way to customize VoodooPS2 is pretty weird, you have to familiar with ACPI, because RehabMan is familiar with ACPI thus he prefers that way to tune the VoodooPS2. So, you know this makes all of our life become tough. If you know more about hackintosh, you will know which way is reliable: any kernel extension will inheritance IOKitPersonality natively. But load ACPI and then read information from SSDT will sometimes fail. It's definitely gorgeous useless function. Same example can be found in CodecCommander...
- If you have chance to install 10.11.6 with AppleSmartTouchPad, you will know AppleSmartTouchPad has a totally different level than VoodooPS2. 

Since the author of AppleSmartTouchPad's bugs is close to finish, I just want to use that great project. That's it.

Thanks,
syscl

**Comment by bdurrow** [comment]
I can confirm that AppleSmartTouchPad 4.7 Beta 5 resolves most of the usability issues and the trackpad System preference pane works without any additional installation or patch.  For reference I downloaded that Beta from the bottom of the first post here: http://forum.osxlatitude.com/index.php?/topic/1948-elan-focaltech-and-synaptics-smart-touchpad-driver-mac-os-x/

Thank you for your advice.
