### ISSUE TITLE
Sleep == Shutdown

### ISSUE THREAD

**Issue by arbitary** [syscl/XPS9350-macOS#42]
Every time I put the laptop into sleep, it turns itself off. Is there a way to fix this?

**Comment by niklasbeinghaus** [comment]
Duplicate with? #26

**Comment by arbitary** [comment]
HWP was never enabled.

**Comment by syscl** [comment]
Hi @arbitary and @niklasbeinghaus 

XPS 13 9350 has been proved to sleep normally. But there's two things need to be careful about sleep:
- DW 1820 will cause com.apple.driver.AirPort.Brcm4360 panic. Because DW 1820 behaves unstable on Sierra, what's worse, we can't power DW 1820 correctly on XPS 13 9350.
- Sleep seems to cause data corruption, very rare, but the reason remains unknown. I and other people are still trying to figure out what cause the the problem.

BTW, hwp has been enabled if you pay attention to ```IA32_PM_ENABLE``` register, the value soon tell you the truth. 0x1 stands for enable, 0x0 for disable. But at this stage, power management with HWP is incomplete. Better to wait for me releasing a SSDT-pr + freqv update for full power management.

That's it,
syscl

**Comment by arbitary** [comment]
Just to confirm that the problem was indeed caused by the DW1820 adapter. I disabled it in the BIOS and the problem disappeared. Thanks @syscl

**Comment by syscl** [comment]
@arbitary Nice.
