### ISSUE TITLE
Instructions in Readme.md

### ISSUE THREAD

**Issue by R1MnTnA** [syscl/XPS9350-macOS#43]
Hi @Syscl,

I see that you only changed one option in your bios in the instructions, but in other guides they say to turn off other features such as the ones below.- Could this cause a problem if these are not set correctly? 

BIOS Settings:
- SATA: AHCI
- USB security level: disabled
- Disable SD card reader (saves 0.5W of power)
- TPM Off
- Deactivate Computrace
- Disable Secure Boot
- Disable Wake on USB-C Dell Dock
- Disable VT-D
- Auto-OS recovery threshold: OFF
- SupportAssist OS Recovery: OFF

**Comment by syscl** [comment]
@R1MnTnA If you want better power consume, disable SD card reader(saved 1.5W of power) as well.

No need to change other section, just leave it as default. My instruction targets at making people's life as simple as it can be.

syscl

**Comment by R1MnTnA** [comment]
@syscl, understood, but I thought the VT-D or some other features can cause problems for mac os, if not set correctly.

**Comment by syscl** [comment]
VT-d has already solved by ```dart=0``` in Clover config.plist. Or we can drop it by dmar table, same method to resolve VT-d problem. I don't think disable VT-d in BIOS is a good solution, because you then lost VT-d support in both Windows and Linux if you have multi systems. Though you can tune your BIOS if you like(because deploy.sh provide this great flexibility for you).

syscl

**Comment by R1MnTnA** [comment]
Oh, okay. Thank you for that info. Very good to know. Nice work as always. 😉👍🏼
