### ISSUE TITLE
Issue switching from NVMe kexttopatches to HackrNVMeFamily

### ISSUE THREAD

**Issue by Helicoss** [syscl/XPS9350-macOS#50]
First of all a huge thank you for all your hard work, this is by far the most complete hackintosh setup I have used for the XPS 13.

I had a minor issue/question related to it I was wondering if you could help resolve. I'm trying to drop the NVMe kexttopatches and set them up as a kext + SSDT using [rehabman's guide](https://www.tonymacx86.com/threads/guide-hackrnvmefamily-co-existence-with-ionvmefamily-using-class-code-spoof.210316/). The issue is that it doesn't seem to work and my guess is it's because the original ACPI path for the SSD is SB.PCI0.RP09.PXSX, but using your patches PXSX gets patched to SSD0 instead.

I've tried creating and SSDT for PXSX and one for SSD0 and neither of them work. Do you know if it's possible to install HackrNVMeFamily with the SSD0 patch or do you recommend just leaving the kexttopatches in clover instead with the current setup?

**Comment by furrybanana** [comment]
What NVMe SSD do you have in your XPS?
If you follow the guide and copy the Clover from this git to macOS install disk for the vanilla installation, it should show the NVMe in Disk Utility. After installing macOS and dumping SSDT you should be able to deploy the script.

It works on my Samsung NVMe PM951 256GB disk.

**Comment by R1MnTnA** [comment]
Please see issue #25

**Comment by Helicoss** [comment]
I'm using a 512GB Samsung 950 Pro but I'm not having a problem with the installation or anything. I'm just trying to clean up my kexttopatches folder as Rehabman recommends against leaving NVMe patches there and using HackrNVMeFamily kext instead

**Comment by R1MnTnA** [comment]
Please see issue #25

**Comment by Helicoss** [comment]
oops didn't mean to close issue, @R1MnTnA I am trying to clean up config file for use with HackrNVMeFamily instead, the installation is already successful

**Comment by syscl** [comment]
Why use HackrNVMeFamily? I see no way using this method. 

- Complex to implement
- Only works on specific computer, you need to tune ACPI table manually, thus not be applicable
- You need to wait author's update, otherwise, you have to wait 

If you are afraid of data lose due to update, why not use a dummy kext with Piker's patches on it?  That will be much simpler and better. 

Friends keep in mind, the first thing in hackintosh is to make things work, that's the most important thing. Then we consider elegant method and general solution. I saw hundreds of posts and mails asking me the same question: why ```Class-spoof``` method does not work? I don't want to answer same question endlessly. Again, if you prefer so call ```safe``` method, just run Micky1979's script after finishing install, that's good enough. Otherwise, please, don't ask me how to use HackrNVMeFamily method again!

Thank you,
syscl

**Comment by Helicoss** [comment]
Thank you, sorry to bother but this more than answers all my questions, much appreciated
