### ISSUE TITLE
Installation script assumes EFI is mounted in /Volumes/EFI

### ISSUE THREAD

**Issue by kultigspritzig** [syscl/XPS9350-macOS#53]
OS X mounts according to the label, which can be ESP instead of EFI. Script should check for user-indicated partition's label before mounting the volume, instead of assuming /Volumes/EFI mount point

**Comment by syscl** [comment]
I am not assuming, it's by standard on a real Mac. You can use any of the name for ESP you want, but why should I buy your mistake?

syscl

**Comment by kultigspritzig** [comment]
"My mistake"? This is a proper label for this partition:
https://en.wikipedia.org/wiki/EFI_system_partition?wprov=sfsi1

This is also what Windows will name it. Which is what a lot of people will
have installed.

Also, drop the attitude. There's no need for the douchebaggery.

**Comment by syscl** [comment]
Windows use no tile for EFI/ESP if my memory don't get mess. But if you use Disk Utility to initial your hard disk on laptop, macOS will assign EFI to partition with uuid ```C12A7328-F81F-11D2-BA4B-00A0C93EC93B```. There's copious amount of methods to detect a right ESP's mount name, if you watch my code writing for Clover's 80.save_nvram_plist.local.

And yes, in M3800 project, there's already ESP partition detection. But I won't try to implement this function soon, because I have no time to fix it up. It will not that tough, but I need to fix other important issue for our XPS 13 9350 at this moment. 

I received hundreds of mails asking about similar questions per days, I know what problems will occur because we are using the same laptop. But, at this moment, please let me focus on some major bug like NVRAM script refine and sleep will cause data corruption in some rare case.

If you have time, don't hesitate to pull merge to make this project better!

Thank you,
syscl

**Comment by nos1609** [comment]
I'm rewriting the script each time I update the setup also, since have the same path as @kultigspritzig stated. 
@syscl a different partition name is not the mistake, it was intentionnaly done to work with external drives more easly, since macOS mounts drives using lables and you can't acces them by nodes, like it's done in linux. So when you connect an external drive which used to be internal in another laptop it's quite messy finding which one of the mounted EFI partitions is the right one to operate with. Since that I see no point in entering the partition node in the script as the path is hardcoded. Some people are using clover on an external USB-key, so this make it also impossible to proceed with the script, as the USB efi partition will always "EFI 2", and nod simply "EFI" in the path.

**Comment by syscl** [comment]
Hi @kultigspritzig @nos1609 Please try the latest deploy.sh to see if it fix the ESP mount issue!

Have a good day,
syscl

**Comment by kultigspritzig** [comment]
@syscl I re-labeled my EFI partition already, but looking at the commit it looks fine to me.

**Comment by nos1609** [comment]
@syscl it works!
